### ISSUE TITLE
How to handle floating-point array indices in Neo?

### ISSUE THREAD

**Issue by AlienKevin** [douglascrockford/howjavascriptworks#11]
Dear Mr. Crockford,
I like your idea of combining floats and ints into one number type. One unified number type makes sense for most math operations and saves a lot of headache associated with handling two number types. However, when we are doing array indexing, how can we handle floating-point indices? I know that all array indices in JavaScript are strings so you can store values into floating-point indices:
```js
let a = []
a[1.5] = 10
console.log(a[1.5]) // outputs: 10
```
To me, JS's behavior is both strange and confusing as many people including me regard array indices as whole numbers and expect JS to floor or round floating-point indices to whole numbers.
What approach do you recommend to deal with floating-point indices? Is this a necessary evil for adopting a unified number type?

**Comment by douglascrockford** [comment]
I agree that JS is much too permissive here. Strings should not be used as array indexes. 
On reading, a[1.5] should produce null because there is no such element. 
On writing, it should fail.

**Comment by ray1345** [comment]
Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Douglas Crockford <notifications@github.com> Date: 11/15/19  8:38 PM  (GMT-05:00) To: douglascrockford/howjavascriptworks <howjavascriptworks@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [douglascrockford/howjavascriptworks] How to handle
  floating-point array indices in Neo? (#11) Closed #11.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/douglascrockford/howjavascriptworks/issues/11?email_source=notifications\u0026email_token=ANO4QDXUDV3KXB44SGTTURTQT5FJXA5CNFSM4JOCVYS2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU4UDLHI#event-2804430237",
"url": "https://github.com/douglascrockford/howjavascriptworks/issues/11?email_source=notifications\u0026email_token=ANO4QDXUDV3KXB44SGTTURTQT5FJXA5CNFSM4JOCVYS2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU4UDLHI#event-2804430237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
